---
title: "About Me"
output: 
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
    #code_folding: hide
---

<style type="text/css">
.title {
  display: none;
}


</style>
<div class = "row" style = "padding-top: 40px;">

# Who am I?

Hi! My name is Brian Forristal. Welcome to my personal website. Here, I host various coded examples of data science and statistics applications I've learned during my time at the University of Pittsburgh. By no means is this an exhaustive list of all my work, but a carely curated subset of key ideas and methods I find to be the most intuitive and useful. 

I am currently a full-time student at the University of Pittsburgh and will be completing my BS in Statistics in the spring of 2021. Prior to going back to university, I gained valuable work and life experience in the telcommunications industry. For more details, checkout my [resume](https://github.com/Brian031188/Portfolio3/blob/master/Resume/CV_BrianForristal.pdf) or [LinkedIn profile](https://www.linkedin.com/in/brian-forristal-b84088a6/).

I believe it is paramount to be well-rounded and knowledgeable in many disciplines, that way I can maximize my contributions to the team. 

# Goals
1. Be the best dad I can be :)
2. Hoping to find a meaningful job in data science and statistics where I can make positive change.
3. Change the world!

# Credentials
LinkedIn Profile: [Brian Forristal](https://www.linkedin.com/in/brian-forristal-b84088a6/)

Resume: [Click Here](https://github.com/Brian031188/Portfolio3/blob/master/Resume/CV_BrianForristal.pdf)

Unofficial Transcript: [Fall 2020](https://github.com/Brian031188/Portfolio3/blob/master/Transcript/PITT_TSRPT.pdf)

# Academic Papers
Title: 
Course

Title
Course:

</a>
</div>
